language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Vlgc9Q+giKZatyuxo/+8cBAtVnQJG7kU5eK0H2uCgeq9Ghqfji3PW0U4bJAU9gMvcx235DTsx1bKP/amCDL1oGJxWRfDdFQ6T7S9E1JlGOIA7n4S/+POAZBKod062U7Xy+vKGD2POQKPcMjBMX9jNNT5Boi41X+4EzAi7sndKCuKq8kTGbjHg2ESF/bnGYZoRVSUiT00FhwRyPvC09eXov/6pkkDzcr9YK0QgPtBV5mRLVqxbBZk2t6ZUt1T007JFNbWLQ83J3tJOjkZ3BORmMu9rtwghVa4ceV3wIMAKg9BmBCoVxowy5zDgi2XkUu7E9zBk8/+YYO35YWRhQnwCOVQNh4YpEw01yoMqJ52MlFc/Xc7VMKyo+p47Hs+PpMpHBlxxUNQ7YtS6dnVqpPmL2FfSD/dw1LV1Xjp3AolS0wUotGuSBlAZKPnAYvxaPeMatzE+bC2+Jk8LJbMLQs0wQELMJyx8rcCbPnz4RNou6rpk68V6BKs8Rvj37n9as7pAPF68GdxCgk4PB56g4gnd/3wnu0gqILsxI8brH1LrnX5MFmYoOh+0tDYlIcT8mNx/3eZvyRqK2bn8W1/NttfyanMzKAPkn0k18Qd9z1oOx/EbDZz7ah/1pi6klGrWSEzw7tZC//s+5ZEhUiP4WIYOtJlgtXG9yHZevASppv+Bd0=
  file:
    - 'mapz.js'
    - 'mapz.min.js'
  on:
    tags: true
